### ISSUE TITLE
First rendering low performance on SVG animation

### ISSUE THREAD

**Issue by duranmla** [simian-ci/simian-ci.github.io#51]
# Context

On retina displays, the animation for the lead SVG looks choppy and seems to be an expected behavior which we need to fix for those users if you want to know more about the issue take a look at:

- http://www.crmarsh.com/svg-performance/

## Acceptance Criteria

* Retina display users should be able to see the website without any performance issues

> It would be great if we can target only retina display users so we are able to show the animation where there is no performance issues

**Comment by orlando** [comment]
Fixed on #54
